name: Build and Test TodoApi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
          ports:
            - 1433:1433
          options: >-
            --name sqlserver
            --health-cmd "exit 0"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TodoDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
        run: dotnet test --no-build --verbosity normal
